\spring:
  config:
    activate:
      on-profile: dev

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://mysql-dev-test.cnbw1f0cb00s.ap-northeast-2.rds.amazonaws.com:3306/devtest?characterEncoding=utf8&useSSL=false&autoReconnection=true&serverTimezone=UTC
      username: admin
      password: devtest1234
      driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    lettuce:
      pool:
        max-active: 5
        max-idle: 5
        min-idle: 1
    port: 6379
    host: localhost

  mvc:
    throw-exception-if-no-handler-found: true

  devtools:
    livereload:
      enabled: true
    thymeleaf:
      cache: false

# apis
externals:

internals:

logging:
  config: classpath:logback/logback-dev.xml
